### ISSUE TITLE
ORCID-Timeline component

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#10]
### DESC
- add ORCID-Timeline component

### TODOs
- [x] add component sceletion for OrcidTimeline
- [x] expose styling prop to outside
- [x]  for educational data
- [x] for employment data
- [x] for works
- [x] able to pass through custom JSX (for rendering links and additional stuff)
- [x] add own orcid Timeline Component that handles conversion of data to correct model
