### ISSUE TITLE
Add to ORCID additional information

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#11]
### DESC
- check for additional meaningful fields etc. in ORCId
- supply updated data

### TODOS
- [x] add membership of eadh
- [x] add membership of dhd
- [x] add: helped on TEI conference --> a service in terms of orcid
- [x] add: helped add summer school -> a service in term of orcid
- [x] add published DERLA project
- [x] add contribution to FORGE poster?
- [x] what about mentions of DERLA in orf.at ? somewhat usable? 
- [x] add: I'm part of KONDE
- [x] add: publications on digitale-edition.at
- [x] check chpollin page for insipiration
- [x] check sarah lang page for inspiration
- [x] check other ZIM members for inspirations for what to add to the CV!
- [x] add conference presentation of cantus
- [x] add conf presentation of derla zeitgeschichtetag
- [x] change from services to conference abstracts?
- [x] take a look at Forschungsportal and add things from there to ORCID
- [x] check if current entries are true / need update
- [x] add things documented add DERLA project
- [x] what about the frontend-devtools page on github??
- [x] add teaching of "Einführung in die Informationsmodellierung"
- [x] add link to npmjs account!
- [x] add software published on npmjs -> add more todos
- [x] add zim-fuzzysearch software
- [x] add zim-graphviz as software
- [x] add zim-gamshooks as software
- [x] add gams.js as software-library
- [x] add gams-wippets as part of software collaboration
- [x] add gams frontend templates as software I maintain
- [x] add cantus nlp-app vue github
- [x] add loadstyler github
- [x] cantus Triple Form
- [x] add gams - lib folder 
- [x] add NAMPI backend / frontend?
- [x] add react mapp of DERLA 
- [x] add two presentations on future conference for DERLA
- [x] add that I'm part of the development team of GAMS as frontend and backend developer 
- [ ] Leistungsstipendien eintragen
- [x] add more todos
