### ISSUE TITLE
Add sidebar for github / etc.

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#14]
### DESC
- should include some icons so the page looks more friendly

### TODOs
- [x] add github icon
- [x] ORCID icon
- [x] NPMJS icon
- [x] Twitter icon
- [x] refactor to own component
- [x] mail icon link
- [x] refactor to use the plain orcid person response 
- [x] google scholar icon link?
- [x] ZIM Graz link
- [x] link to pdf cv?
- [x] add more icon links?
