### ISSUE TITLE
General entry page styling

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#17]
### DESC
- general issue for changing the styles of the entry page

### TODOs
- [x] timelines should have the same modes
- [x] add Hire me button somewhere -> next to intern-nav buttons ?
- [x] add dates to educations and qualifications
- [x] add more todos
