### ISSUE TITLE
SEO: Add React Helmet to page

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#19]
### DESC
- improve lighthouse scoring of page!
- use http://linter.structured-data.org/ to improve RDFA of page like that it contains stmt about person with specified URI
- USE THIS: https://webcode.tools/generators/open-graph/article
- JSON-lD on the website:  https://nystudio107.com/blog/json-ld-structured-data-and-erotica 

### TODOs
- [x] install React Helmet
- [x] add dublin core rdfa to head
- [x] whats with keywords in metatags?
- [x] add in schema.org namespace
- [x] add in some schema.org meta tags
- [x] point via RDFA to ORCID URI --> in meta tag head
- [ ] provide whole pages / components with more structured data in body tag as in examples for rdfa on schema.org
- [x] add in meta tags for schema.org
- [ ] add in foaf namespace
- [ ] add in foaf stuff as meta tags?
- [x] add in alt attributes for images in iconbar
- [x] add apple touch shizzle (+ attribution "Apple icon by Icons8")
- [x] add attribution section in imprint and paste in: "Apple icon by Icons8" for the applied apple touch icon
- [ ] would be much more intelligent via graphql API https://www.gatsbyjs.com/docs/add-seo-component/
- [x] add open graph protocol things (https://ogp.me/)
- [x] SEO with Gatsby (https://www.gatsbyjs.com/docs/add-seo-component/)
- [x] add own head component that handles adding the metadata via helmet?
- [x] add base impl

**Comment by Schiller-Stoff** [comment]
outdated
