### ISSUE TITLE
Add basic portfolio template files

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#2]
### DESC
- after typescript etc has been setup
- add according to this template: https://github.com/smakosh/gatsby-portfolio-dev

### TODOs
- [x] setup base react-bootstrap integration etc.
- [x] add basic assets to static folder /img 
- [x] add fonts of template
- [x] add base template files 
- [x] make fully working (with limited features / not everything should work according to template )
