### ISSUE TITLE
Add more pages / finish nav linkings?

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#20]
### DESC
- some links in the nav are rendered according to ORCID / others need to be statically assigned? (like imprint / data protection / others?)
- maybe best would beto contain ORCID links in a dropdown?
- add more pages like contact / about

### TODOs
- [x] add imprint page with necessary acknowledgements
- [x] contain Orcid links inside dropdown!
- [x] add data protection page ---> added to imprint
- [x] implement
- [x] Add contact page
- [x] Add generic content to imprint?
- [x] is an about page really necessary?
