### ISSUE TITLE
Nav should by generated / make use of orcid data?

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#25]
### DESC
- nice
### TODOs
- [x] allow BaseLayout to accept a nav as property
- [x] add ORCID data to nav
- [x] think about how to implement best
