### ISSUE TITLE
OrcidNav component

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#26]
### DESC
- create orcid specific nav component

### TODOs
- [x] adapt base Nav
- [x] build name
- [x] build navigation according to returned orcid stuff
- [x] create OrcidNav component
- [x] use OrcidNav in index page
