### ISSUE TITLE
Website findability: Add links to my personal page

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/Stoff-Sebi.github.io#27]
### TODOs
- [x] github to page?
- [x] google scholar to page?
- [x] forschungsportal to page?
- [x] orcid to page?
- [x] twitter
- [x] facebook to webpage
- [x] other social media places to my website
- [x] Linked in
- [x] update Forschungsportal
- [x] update google scholar (see other issue)
- [x] pinterest
- [x] npmjs
- [x] github
- [x] facebook
- [x] add link to DERLA AND cantus! (other ZIM projects?)
- [x] add more places!

**Comment by Stoff-Sebi** [comment]
updated
