### ISSUE TITLE
Power up google scholar profile

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/Stoff-Sebi.github.io#28]
### DESC
- add content / articles i have written to google scholar

### TODOs
- [x] add in theses i have written
- [x] add profile picture
- [x] add link to my personal website on github!! (or buy namespace?)
- [x] add in more publications manually like konde weißbuch?
- [x] add in conferences
- [x] orientate on orcid

**Comment by Stoff-Sebi** [comment]
updated
