### ISSUE TITLE
Improve general design

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#35]
### DESC
- issue for improving general design aspects of the page
- according to: https://themes.3rdwavemedia.com/devcard/bs5/

### TODOs
- [x] imprint should have same design as entry page
- [x] correct nav linking in sidebar
- [x] add own contact page?

**Comment by Stoff-Sebi** [comment]
implemented
