### ISSUE TITLE
Deploy first version of page

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/Stoff-Sebi.github.io#37]
### DESC
- https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
- https://hackernoon.com/how-to-set-up-godaddy-domain-with-github-pages-a9300366c7b
- https://jinnabalu.medium.com/godaddy-domain-with-github-pages-62aed906d4ef

### TODOs
- [x] cv repo needs to be public
- [x] gh-pages branch: create deployment env on github
- [x] build gatsby -> with corrected build env variable pointing to https://stoff-sebi.github.io/ in production
- [x] check deployment
- [x] add forwarding from godaddy to github pages!
- [x] fix basic lighthouse errors
- [x] custom domain setup
- [x] setup
- [x] create own branch / release for the page

**Comment by Stoff-Sebi** [comment]
released page
