### ISSUE TITLE
Test out data stories 

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/Stoff-Sebi.github.io#40]
### DESC
- try out to create scrollitelling via react scrollama https://github.com/jsonkao/react-scrollama
- react scrollama produces weird gatsby errors https://www.npmjs.com/package/scrollama

### TODOs
- [x] test out react-scrollama --> error with react
- [x] test out scrollama js 
- [x] create demo / test stories page
- [x] Legendbox should be controllable for each step
- [ ] create a data story with derla data?
- [ ] write a markdown blog post about experience using react-scrollama with gatsby
- [ ] implement

**Comment by Stoff-Sebi** [comment]
implemented
