### ISSUE TITLE
Try without plugin: Basic sourcing from orcid

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#7]
### DESC
- according to https://www.gatsbyjs.com/docs/how-to/querying-data/using-gatsby-without-graphql/
- https://www.gatsbyjs.com/docs/content-and-data/

- how to add data to existing pages??? (without own plugin)

### TODOs
- [x] import template typing from json2ts.com
- [x] add basic typing and show some content on a page
- [x] add env variable setup (according to: https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/)
- [x] implement
