### ISSUE TITLE
Add basic profile picture

### ISSUE THREAD

**Issue by Schiller-Stoff** [Stoff-Sebi/Stoff-Sebi.github.io#8]
### DESC
- refine styling etc. for the page

### TODOs
- [x] add basic profile picture
- [x] redo some styling
- [ ] refactor to own component / components
