### ISSUE TITLE
Switch between different CV styles?

### ISSUE THREAD

**Issue by Stoff-Sebi** [Stoff-Sebi/Stoff-Sebi.github.io#9]
### DESC
- need to present ourselves as researcher / humanists / developers / programmers

### TODOs
- [ ] I'm a developer --> switch to developer style CV
- [ ] I'm a researcher --> switch to academic style CV
- [ ] I'm a --> add additional points here?

**Comment by Stoff-Sebi** [comment]
not necessary
